spring.application.name=ubi-backend
opensearch.url=https://localhost:9200
opensearch.username=admin
opensearch.password=${OPENSEARCH_PASSWORD}

spring.data.mongodb.uri=mongodb://localhost:27017/shopease

spring.ssl.bundle.jks.opensearch.truststore.location=file:${user.home}/opensearch-truststore.p12
spring.ssl.bundle.jks.opensearch.truststore.password=${OPENSEARCH_TRUSTSTORE_PASSWORD}
spring.ssl.bundle.jks.opensearch.truststore.type=PKCS12